### ISSUE TITLE
Documentation missing name: authority-0 in ClusterImagePolicy

### ISSUE THREAD

**Issue by brilong** [chainguard-dev/edu#2219]
**Describe the bug**
In the [documented ClusterImagePolicy for verifying Chainguard images](https://edu.chainguard.dev/open-source/sigstore/policy-controller/policies/using-policy-controller-to-verify-signed-chainguard-images/#step-2--creating-a-clusterimagepolicy), ArgoCD showed the policy was out of sync until I added `name: authority-0`. 

**To Reproduce**
1. Deploy the ClusterImagePolicy as documented using ArgoCD.
2. ArgoCD shows out of sync.

**Expected behavior**
ArgoCD shows Synced.

**Additional context**
The following policy applied and shows synced.
```
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: chainguard-images-are-signed
  annotations:
    catalog.chainguard.dev/title: Chainguard Images
    catalog.chainguard.dev/description: Enforce Chainguard images are signed
    catalog.chainguard.dev/labels: chainguard
spec:
  images:
    - glob: cgr.dev/chainguard/**
  authorities:
    - keyless:
        url: https://fulcio.sigstore.dev
        identities:
          - issuer: https://token.actions.githubusercontent.com
            subject: https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main
      ctlog:
        url: https://rekor.sigstore.dev
      name: authority-0
```
