### ISSUE TITLE
Headers content

### ISSUE THREAD

**Issue by ltagliaferri** [chainguard-dev/edu#8]
For discussion — I wanted to know what we think about the current headers @jamonation @erikaheidi 

For example, on the tutorial about how to sign an SBOM, they look like this in markdown:

```
---
title: "How to Sign an SBOM with Cosign"
type: "article"
description: "Signing software bills of materials with Cosign"
lead: "Use Cosign to sign a software bill of materials"
date: 2022-13-07T15:22:20+01:00
lastmod: 2022-13-07T15:22:20+01:00
draft: false
images: []
menu:
  docs:
    parent: "sigstore"
weight: 620
toc: true
---
```

On the site it looks like this:

<img width="744" alt="Screen Shot 2022-07-13 at 10 35 39 PM" src="https://user-images.githubusercontent.com/5977693/178885877-60d40787-164c-4caa-8f52-2482e0898d89.png">

We don't have the lead or description coming into the blog post cards:

<img width="764" alt="Screen Shot 2022-07-13 at 10 37 00 PM" src="https://user-images.githubusercontent.com/5977693/178886063-075fe74f-598a-467b-b524-4e479cdda623.png">

But the `description` I believe will be indexed by search engines.

We also don't have the date coming into the front end.

In terms of authors, we don't have authors either in the headers or on the frontend. And we may want to have that as well as author landing pages. But authorship may be less important for straight documentation.

What are your thoughts?
